services:
  # The Database
  mongo:
    image: mongo:latest
    container_name: wordsynk-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # The Web GUI (Optional)
  mongo-express:
    image: mongo-express
    container_name: wordsynk-admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
